services:
    SSO\FpBundle\Controller\FactoryPortalConnect:
        calls:
            - method: setContainer
        arguments: ['@service_container']
    SSO\FpBundle\Controller\SSO\Logout:
        arguments:
            $factoryPortalUrl: '%env(FACTORY_PORTAL_LOGOUT)%'

    SSO\FpBundle\Provider\FactoryOauth2ClientProvider:
        arguments:
            $options: { clientId: '%env(OAUTH_FACTORY_PORTAL_ID)%', clientSecret: '%env(OAUTH_FACTORY_PORTAL_SECRET)%' }
        public: true

    app.factory.provider:
        alias: SSO\FpBundle\Provider\FactoryOauth2ClientProvider



    KnpU\OAuth2ClientBundle\Client\OAuth2Client:
        arguments:
            $provider: '@app.factory.provider'
